<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <!--<NoWin32Manifest>False</NoWin32Manifest>-->
    <!--<NoStdLib>False</NoStdLib>-->
    <UseWindowsForms>true</UseWindowsForms>
    <!--<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>-->
    <!--<PostBuildEvent>"%25windir%25\Microsoft.NET\Framework\v4.0.30319\regasm.exe" "$(TargetPath)" /codebase /tlb</PostBuildEvent>-->
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <IsPackable>true</IsPackable>
  </PropertyGroup>
</Project>